### ISSUE TITLE
提bug和优化建议

### ISSUE THREAD

**Issue by iamvicliu** [suxin1995/BaibuTieba-Sign#2]
1、贴吧APP扫码登录后，必须手动关闭二维码图片，程序才会继续运行
2、希望可以存储身份，如果有身份则不需扫码

**Comment by iamvicliu** [comment]
电脑签到成功
photoshop签到成功
去哪儿签到成功
英雄联盟之极品天才签到成功
英雄联盟之极品天才签到成功

Traceback (most recent call last):
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='tieba.baidu.com', port=80): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\vicli\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\vicli\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\vicli\.vscode\extensions\ms-python.python-2019.8.30787\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\OneDrive\Python\BaibuTieba-Sign-master\tieba_sign.py", line 195, in <module>
    tieba.main()
  File "d:\OneDrive\Python\BaibuTieba-Sign-master\tieba_sign.py", line 152, in main
    self.sign_one(n)
  File "d:\OneDrive\Python\BaibuTieba-Sign-master\tieba_sign.py", line 108, in sign_one
    fid =self.get_fid(name)
  File "d:\OneDrive\Python\BaibuTieba-Sign-master\tieba_sign.py", line 37, in get_fid
    fid = requests.get(url,timeout=2).json()['data']['fid']
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\vicli\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='tieba.baidu.com', port=80): Read timed out. (read timeout=2)
PS D:\OneDrive\Python>

**Comment by suxin1995** [comment]
> 1、贴吧APP扫码登录后，必须手动关闭二维码图片，程序才会继续运行
> 2、希望可以存储身份，如果有身份则不需扫码

**Comment by xsu-git** [comment]
好久忘了回复   感谢你的建议
1.   并不是关了二维码程序才会继续运行  因为没有监听扫描回调函数  没法及时判定是否扫描成功  所以偷懒强行等待15s扫描时间  而我的mac环境运行matlab库自动关闭图片有点问题  所以没让它自动关闭
2.  抽空新增了cookie留存功能  cookie失效的判定有待测试

**Comment by Testplayers** [comment]
能加上server酱推送吗
